### ISSUE TITLE
Plugin is hard-coded to http, so won't work with Chrome from an https site

### ISSUE THREAD

**Issue by sgbeal** [maartendecat/icndb-jquery#1]
The code includes this line:

    var base = "http://api.icndb.com/";

Chrome doesn't allow mixed https/http content. The fix is trivial:

    var base = "//api.icndb.com/";

That will tell it to use whatever protocol the main page is using, as is demonstrated on my site: https://wanderinghorse.net/

**Comment by maartendecat** [comment]
Good point, done!

Can you review on your side whether this fixes your issue?

**Comment by sgbeal** [comment]
i made/tested the change locally before reporting it, so i'm confident that it works :).

**Comment by sgbeal** [comment]
PS: it's been running on my site with that same change since yesterday.
